version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/bitnami/redis/data

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      - CONFIG_FILE=config.env
    depends_on:
      - postgres
      - redis

  backend:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: express-app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    env_file:
      - ./service/.env

volumes:
  postgres_data:
  redis_data:

