# Dockerfile
FROM nginx:1.18.0-alpine

# Set the working directory
WORKDIR /etc/nginx/templates

# Copy your default configuration template into the container
COPY default.conf.template /etc/nginx/templates/default.conf.template

